#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomPage.HangfireExtensions.ManagementPage
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
    using CustomPage.HangfireExtensions.ManagementPage;
    
    #line default
    #line hidden
    
    #line 3 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 5 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Management : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\n");






WriteLiteral("\n");


            
            #line 8 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
  
    Layout = new LayoutPage("Management");

    var tables = new List<Func<RazorPage, MenuItem>>();

    foreach (var table in AvailableTables)
    {
        var segment = $"{ManagementPageExtensions.UrlPath}/{table.Name}";
        tables.Add(page => new MenuItem(table.Name, page.Url.To(segment))
                {
                    Active = page.RequestPath.StartsWith(segment)
                });
    }

    var data = ReadData(CurrentTable);


            
            #line default
            #line hidden
WriteLiteral("<link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 24 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
                                         Write($"/hangfire/{ManagementPageExtensions.UrlPath[1..]}Resources/css/style.css");

            
            #line default
            #line hidden
WriteLiteral("\" />\n<script src=\"");


            
            #line 25 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
         Write($"/hangfire/{ManagementPageExtensions.UrlPath[1..]}Resources/js/vue.global.js");

            
            #line default
            #line hidden
WriteLiteral("\"></script>\n<script src=\"");


            
            #line 26 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
         Write($"/hangfire/{ManagementPageExtensions.UrlPath[1..]}Resources/js/axios.min.js");

            
            #line default
            #line hidden
WriteLiteral("\"></script>\n<script src=\"");


            
            #line 27 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
         Write($"/hangfire/{ManagementPageExtensions.UrlPath[1..]}Resources/js/app.js");

            
            #line default
            #line hidden
WriteLiteral("\"></script>\n<div class=\"row\">\n    <div class=\"col-md-3\">\n        ");


            
            #line 30 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
   Write(Html.SidebarMenu(tables));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    <div class=\"col-md-9\">\n        <h1 class=\"page-header\">");


            
            #line 33 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
                            Write(CurrentTable.Name ?? "Management");

            
            #line default
            #line hidden
WriteLiteral("</h1>\n");


            
            #line 34 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
         if (tables.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\n                No tables configure" +
"d\n            </div>\n");


            
            #line 39 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div id=\"app\" data-rows=\"");


            
            #line 42 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
                                Write(JsonConvert.SerializeObject(data.Select(x=>JsonConvert.SerializeObject(x))));

            
            #line default
            #line hidden
WriteLiteral("\" data-save-url=\"");


            
            #line 42 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
                                                                                                                              Write($"/hangfire/{ManagementPageExtensions.UrlPath[1..]}Actions/Save");

            
            #line default
            #line hidden
WriteLiteral("\" data-table-name=\"");


            
            #line 42 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
                                                                                                                                                                                                                   Write(CurrentTable.Name);

            
            #line default
            #line hidden
WriteLiteral(@""" class=""js-jobs-list"">
                <div class=""alert alert-success"" v-show=""showSuccessNotification"" style=""display: none"">Settings are saved</div>
                <div class=""alert alert-danger"" v-show=""showErrorNotification"" style=""display: none"">Settings aren't saved</div>
                <div class=""form-item"">
                    <label class=""form-item__label"">Server Type</label>
                    <div class=""input__wrapper"">
                        <select name=""serverType"" class=""input__inner"" v-model=""settings.serverType"">
                            <option value=""SRV1"">SRV1</option>
                            <option value=""SRV2"">SRV2</option>
                            <option value=""SRV3"">SRV3</option>
                        </select>
                    </div>
                </div>
                <div class=""form-item"">
                    <label class=""form-item__label required"">Server Url</label>
                    <div class=""input__wrapper"">
                        <input type=""text"" required=""required"" class=""input__inner"" v-model=""settings.serverUrl"" ");


WriteLiteral(@"@input=""validate""/>
                    </div>
                    <div class=""form-item__error"" v-show=""showValidationError"" style=""display:none"">
                        Please input the server url
                    </div>
                </div>
                <div class=""form-item"">
                    <label class=""form-item__label"">Username</label>
                    <div class=""input__wrapper"">
                        <input type=""text"" class=""input__inner"" v-model=""settings.username"" />
                    </div>
                </div>
                <div class=""form-item"">
                    <label class=""form-item__label"">Password</label>
                    <div class=""input__wrapper"">
                        <input type=""text"" class=""input__inner"" v-model=""settings.password"" />
                    </div>
                </div>
                <div class=""buttons"">
                    <button type=""button"" class=""management-button success"" ");


WriteLiteral("@click=\"save\">Save</button>\n                </div>\n            </div>\n");


            
            #line 80 "..\..\HangfireExtensions\ManagementPage\Management.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\n</div>");


        }
    }
}
#pragma warning restore 1591
